version: "3.7"
services:
  redis:
    image: redis
    ports:
      - 56739:6379
  localstack:
    image: localstack/localstack
    ports:
      - 4566:4566
  mysql:
    image: mysql
    ports:
      - 53306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=testdb
    volumes:
      - ./testdata/schema:/docker-entrypoint-initdb.d

