services:
  redis:
    init: true
    image: redis
    ports:
      - 6379
  mysql:
    init: true
    image: mysql
    ports:
      - 3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=testdb
    volumes:
      - ./testdata/schema:/docker-entrypoint-initdb.d
  bigquery:
    init: true
    image: ghcr.io/goccy/bigquery-emulator
    platform: linux/amd64
    command: |
      --project=test
    ports:
      - 9050
  redis-cluster-node-1:
    init: true
    image: redis
    command: >
      redis-server --port ${REDIS_CLUSTER_NODE_1_PORT} --cluster-enabled yes --cluster-node-timeout 5000
      --cluster-config-file nodes.conf --appendonly yes
      --cluster-announce-ip redis-cluster-node-1 --cluster-announce-port ${REDIS_CLUSTER_NODE_1_PORT}
    ports:
      - "${REDIS_CLUSTER_NODE_1_PORT}:${REDIS_CLUSTER_NODE_1_PORT}"
  redis-cluster-node-2:
    init: true
    image: redis
    command: >
      redis-server --port ${REDIS_CLUSTER_NODE_2_PORT} --cluster-enabled yes --cluster-node-timeout 5000
      --cluster-config-file nodes.conf --appendonly yes
      --cluster-announce-ip redis-cluster-node-2 --cluster-announce-port ${REDIS_CLUSTER_NODE_2_PORT}
    ports:
      - "${REDIS_CLUSTER_NODE_2_PORT}:${REDIS_CLUSTER_NODE_2_PORT}"
  redis-cluster-node-3:
    init: true
    image: redis
    command: >
      redis-server --port ${REDIS_CLUSTER_NODE_3_PORT} --cluster-enabled yes --cluster-node-timeout 5000
      --cluster-config-file nodes.conf --appendonly yes
      --cluster-announce-ip redis-cluster-node-3 --cluster-announce-port ${REDIS_CLUSTER_NODE_3_PORT}
    ports:
      - "${REDIS_CLUSTER_NODE_3_PORT}:${REDIS_CLUSTER_NODE_3_PORT}"
  redis-cluster-init:
    image: redis
    command: >
      sh -c "sleep 3 && redis-cli --cluster create
      redis-cluster-node-1:${REDIS_CLUSTER_NODE_1_PORT}
      redis-cluster-node-2:${REDIS_CLUSTER_NODE_2_PORT}
      redis-cluster-node-3:${REDIS_CLUSTER_NODE_3_PORT}
      --cluster-replicas 0 --cluster-yes"
    depends_on:
      - redis-cluster-node-1
      - redis-cluster-node-2
      - redis-cluster-node-3
    restart: "no"
