version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.1
    ports:
      - 59200:9200
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  redis:
    image: redis:6
    ports:
      - 56739:6379
  localstack:
    image: localstack/localstack
    ports:
      - 4566:4566
  mysql:
    image: mysql:5.7
    ports:
      - 53306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=testdb
    volumes:
      - ./testdata/schema:/docker-entrypoint-initdb.d

