// This file is generated by digen. DO NOT EDIT.
package logosdi

import (
  "time"
)

func (d *D) GetString() string {
  return d.Get("String").(string)
}

func (b *B) SetString(v string) {
  b.Set("String", v)
}

func (d *D) GetTime() time.Time {
  return d.Get("Time").(time.Time)
}

func (b *B) SetTime(v time.Time) {
  b.Set("Time", v)
}
