version: '3'
services:
  app:
    container_name: golang-exercise
    image: golang
    volumes:
      - ../:/srv/
    environment:
      - TZ=Asia/Tokyo
    tty: true
    command: bash
    working_dir: /srv
