name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v2
      - run: env | sort

      - run: docker-compose up -d
      - run: make lint
      - run: make test
