name: CI
on:
  push:
    branches:
      - "main"
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
      - name: go fmt .
        run: |
          make fmt
          git diff --exit-code
      - name: t.Parallel チェック
        run: |
          make tparagen
          git diff --exit-code
      - name: go mod
        run: |
          go mod tidy
          go mod download all
          git diff --exit-code
      - run: go vet ./...
      - name: staticcheck
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          install-go: false

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make compose/up
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright-go
            ~/.cache/ms-playwright
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - run: sleep 10s
      - run: docker compose ps
      - run: make test
