name: CI
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          cache: true
      - name: go fmt .
        run: |
          go fmt .
          git diff --exit-code
      - name: go mod
        run: |
          go mod tidy
          go mod download all
          git diff --exit-code
      - run: go vet ./...
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make compose/up
      - run: docker compose ps
      - uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          cache: true
      - uses: iFaxity/wait-on-action@v1
        with:
          resource: localhost:59200
      - uses: iFaxity/wait-on-action@v1
        with:
          resource: localhost:53306
      - uses: iFaxity/wait-on-action@v1
        with:
          resource: localhost:56739

      - run: make test
