name: CI
on: [push]

jobs:
  go-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.x'
      - uses: actions/checkout@v2
      - name: Check go fmt
        run: |
          go fmt .
          git diff --exit-code go.mod
  go-mod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.x'
      - uses: actions/checkout@v2
      - name: Check go mod
        run: |
          go mod tidy
          git diff --exit-code go.mod
  go-vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.x'
      - uses: actions/checkout@v2
      - run: go vet ./...
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.x'
      - uses: actions/checkout@v2
      - run: docker-compose up -d
      - run: docker-compose ps

      - run: docker-compose run app make test
