name: CI
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
      - name: go fmt .
        run: |
          make fmt
          git diff --exit-code
      - name: go mod
        run: |
          go mod tidy
          go mod download all
          git diff --exit-code
      - run: go vet ./...
      - run: make staticcheck
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make compose/up
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright-go
            ~/.cache/ms-playwright
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - run: sleep 10s
      - run: docker compose ps
      - run: make test
